CREATE DATABASE BLUTEL;
USE BLUTEL;

CREATE TABLE CLIENTE (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CPF VARCHAR(11),
    NOME VARCHAR(100),
    CONTATO VARCHAR(11)
);

CREATE TABLE PAGAMENTO (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(100),
    DESCONTO DECIMAL(16,4),
    JUROS DECIMAL(16,4)
);

CREATE TABLE ENDERECO (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    RUA VARCHAR(255),
    CEP VARCHAR(8),
    NUMERO INT,
    COMPLEMENTO VARCHAR(255)
);

CREATE TABLE ORDEM_SERVICO (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_ID INT NOT NULL,
    PAGAMENTO_ID INT NOT NULL,
    ENDERECO_ID INT NOT NULL,
    DATA DATETIME,
    STATUS TINYINT(1),
    CONSTRAINT fk_ordem_cliente FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID),
    CONSTRAINT fk_ordem_pagamento FOREIGN KEY (PAGAMENTO_ID) REFERENCES PAGAMENTO(ID),
    CONSTRAINT fk_ordem_endereco FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ID)
);

CREATE TABLE CLIENTE_ENDERECO (
    CLIENTE_ID INT NOT NULL,
    ENDERECO_ID INT NOT NULL,
    PRIMARY KEY (CLIENTE_ID, ENDERECO_ID),
    CONSTRAINT fk_ce_cliente FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID),
    CONSTRAINT fk_ce_endereco FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ID)
);

CREATE TABLE SERVICO (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VALOR DECIMAL(16,4),
    DESCRICAO VARCHAR(100)
);

CREATE TABLE SERVICO_ORDEM_SERVICO (
    SERVICO_ID INT NOT NULL,
    ORDEM_SERVICO_ID INT NOT NULL,
    PRIMARY KEY (SERVICO_ID, ORDEM_SERVICO_ID),
    CONSTRAINT fk_sos_servico FOREIGN KEY (SERVICO_ID) REFERENCES SERVICO(ID),
    CONSTRAINT fk_sos_ordem FOREIGN KEY (ORDEM_SERVICO_ID) REFERENCES ORDEM_SERVICO(ID)
);